| Group | AI Assisted Reporting | Outcome  |
|-------|-----------------------|----------|
| 1     | No                    | Positive |
| 2     | No                    | Negative |
| 3     | Yes                   | Positive |
| 4     | Yes                   | Negative |
| 5     | Yes + GenAI           | Positive |
| 6     | Yes + GenAI           | Negative |

In [1]:
import polars as pl
import pandas as pd
import pingouin as pg
from scipy.stats import mannwhitneyu

from pyprojroot import here

root_dir = here()

In [2]:
construct_items = {
    "OA": [
        "OA1",
        "OA2",
        "OA3",
        "OA4",
    ],
    "PA": [
        "PA1",
        "PA2",
        "PA3",
        "PA4",
    ],
    "ITU": [
        "IUT1",
        "IUT2",
        "IUT3",
    ],
    "PRIV": [
        "PRIV1",
        "PRIV2",
        "PRIV3",
    ],
    "RA": [
        "RA1",
        "RA2",
        "RA3",
    ],
    "RC": [
        "RC1",
        "RC2",
        "RC3",
    ],
}

In [3]:
# df_raw = pl.read_excel(
#     root_dir / "data" / "codebook_ntnu_survey_2026-05-14_14-00.xlsx", sheet_name="COMPLETE DATASET"
# )

df_raw = pl.from_pandas(
    pd.read_csv(
        root_dir / "data" / "soci" / "0-300" / "cleaned.csv", encoding="ISO-8859-1"
    )
)

In [4]:
df_raw

shape: (318, 70)
┌──────┬────────┬──────┬────────────────┬───┬─────────┬─────────┬─────────┬──────────┐
│ CASE ┆ SERIAL ┆ REF  ┆ QUESTNNR       ┆ … ┆ MAXPAGE ┆ MISSING ┆ MISSREL ┆ TIME_RSI │
│ ---  ┆ ---    ┆ ---  ┆ ---            ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---      │
│ i64  ┆ f64    ┆ f64  ┆ str            ┆   ┆ i64     ┆ i64     ┆ i64     ┆ f64      │
╞══════╪════════╪══════╪════════════════╪═══╪═════════╪═════════╪═════════╪══════════╡
│ 193  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.92     │
│ 195  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.57     │
│ 196  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.91     │
│ 197  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 2.23     │
│ 198  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.05     │
│ …    ┆ …      ┆ …    ┆ …              ┆ … ┆ …       ┆ …       ┆ …       ┆ …        │
│ 642  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.25     │
│ 650  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 1.06     │
│ 651  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 0.78     │
│ 652  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 0.57     │
│ 655  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.52     │
└──────┴────────┴──────┴────────────────┴───┴─────────┴─────────┴─────────┴──────────┘

In [5]:
required_cols = [
    "ATT_SC",
    "CTRL1",
    "GROUP",
    "IUT1",
    "IUT2",
    "IUT3",
    "MARK1",
    "MARK2",
    "mc1",
    "MC2",
    "OA1",
    "OA2",
    "OA3",
    "OA4",
    "PA1",
    "PA2",
    "PA3",
    "PA4",
    "PAKNOW",
    "PRIV1",
    "PRIV2",
    "PRIV3",
    "RA1",
    "RA2",
    "RA3",
    "RC1",
    "RC2",
    "RC3",
    "RD01_CP",
    "RD02_CP",
    "RD02",
    "RISK",
]

In [6]:
reversed_items = ["PRIV3"]

In [7]:
def correct_reversed(df: pl.DataFrame, reversed_items: list):
    return df.with_columns([(8 - pl.col(c)).alias(c) for c in reversed_items])

In [8]:
df = (
    df_raw.filter(
        pl.col("FT02_01") != "MiriamTest",
    )
    .drop_nulls(subset=required_cols)
    .pipe(correct_reversed, reversed_items)
)

In [9]:
df.select(["TIME_SUM"]).with_row_index().plot.scatter(x="index", y="TIME_SUM")

alt.Chart(...)

In [10]:
df

shape: (299, 70)
┌──────┬────────┬──────┬────────────────┬───┬─────────┬─────────┬─────────┬──────────┐
│ CASE ┆ SERIAL ┆ REF  ┆ QUESTNNR       ┆ … ┆ MAXPAGE ┆ MISSING ┆ MISSREL ┆ TIME_RSI │
│ ---  ┆ ---    ┆ ---  ┆ ---            ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---      │
│ i64  ┆ f64    ┆ f64  ┆ str            ┆   ┆ i64     ┆ i64     ┆ i64     ┆ f64      │
╞══════╪════════╪══════╪════════════════╪═══╪═════════╪═════════╪═════════╪══════════╡
│ 193  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.92     │
│ 195  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.57     │
│ 196  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.91     │
│ 197  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 2.23     │
│ 198  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.05     │
│ …    ┆ …      ┆ …    ┆ …              ┆ … ┆ …       ┆ …       ┆ …       ┆ …        │
│ 642  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.25     │
│ 650  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 1.06     │
│ 651  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 0.78     │
│ 652  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 0.57     │
│ 655  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.52     │
└──────┴────────┴──────┴────────────────┴───┴─────────┴─────────┴─────────┴──────────┘

In [11]:
# check if ctl was answered correctly
assert df["CTRL1"].unique().item() == 2

In [12]:
# check if comprehension check was answered correctly
assert df["ATT_SC"].unique().item() == 1

In [13]:
df["GROUP"].value_counts().sort(by="GROUP").plot.bar(
    x="GROUP",
    y="count",
)

alt.Chart(...)

## Cronbachs Alpha

In [41]:
ca_threshold = 0.7


for construct, items in construct_items.items():
    ca = pg.cronbach_alpha(df[items].to_pandas())[0]
    if ca < ca_threshold:
        print(f"Cr. alpha too low for {construct}: {round(ca, 3)} ❌")
    else:
        print(f"Cr. alpha fine for {construct}: {round(ca, 3)} ✅")

Cr. alpha too low for OA: 0.516 ❌
Cr. alpha too low for PA: 0.624 ❌
Cr. alpha fine for ITU: 0.967 ✅
Cr. alpha too low for PRIV: 0.565 ❌
Cr. alpha fine for RA: 0.796 ✅
Cr. alpha too low for RC: 0.662 ❌

In [26]:
construct_items["OA"]

['OA1', 'OA2', 'OA3', 'OA4']

In [28]:
df['OA1', 'OA2', 'OA3', 'OA4'].mean()

shape: (1, 4)
┌──────────┬──────────┬──────────┬──────────┐
│ OA1      ┆ OA2      ┆ OA3      ┆ OA4      │
│ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╡
│ 5.180602 ┆ 5.454849 ┆ 4.675585 ┆ 5.541806 │
└──────────┴──────────┴──────────┴──────────┘

In [29]:
df['OA1', 'OA2', 'OA3', 'OA4'].std()

shape: (1, 4)
┌──────────┬─────────┬──────────┬──────────┐
│ OA1      ┆ OA2     ┆ OA3      ┆ OA4      │
│ ---      ┆ ---     ┆ ---      ┆ ---      │
│ f64      ┆ f64     ┆ f64      ┆ f64      │
╞══════════╪═════════╪══════════╪══════════╡
│ 1.376026 ┆ 1.34631 ┆ 1.706218 ┆ 1.433337 │
└──────────┴─────────┴──────────┴──────────┘

In [39]:
df["OA1", "OA2", "OA3", "OA4"].with_columns(
    OA1 = pl.col("OA1").cast(pl.Int64)
).to_pandas()

     OA1  OA2  OA3  OA4
0      6    2    6    6
1      6    4    7    5
2      5    5    5    6
3      5    5    5    6
4      5    2    5    6
..   ...  ...  ...  ...
294    5    6    6    5
295    6    6    6    6
296    6    6    5    7
297    5    6    5    5
298    2    6    6    7

[299 rows x 4 columns]

In [33]:
pg.cronbach_alpha(df[["OA1", "OA2", "OA3", "OA4"]].to_pandas())

(np.float64(0.5163780160290974), array([0.42, 0.6 ]))

## Manipulation Check

In [19]:
df.group_by("GROUP").agg(pl.col("mc1").std()).sort(by="GROUP")

shape: (6, 2)
┌───────┬──────────┐
│ GROUP ┆ mc1      │
│ ---   ┆ ---      │
│ i64   ┆ f64      │
╞═══════╪══════════╡
│ 1     ┆ 0.867497 │
│ 2     ┆ 1.377562 │
│ 3     ┆ 1.205036 │
│ 4     ┆ 1.07663  │
│ 5     ┆ 1.486301 │
│ 6     ┆ 0.828189 │
└───────┴──────────┘

In [20]:
df.group_by("GROUP").agg(pl.col("mc1").mean()).sort(by="GROUP").plot.bar(
    x="GROUP", y="mc1"
)

alt.Chart(...)

In [21]:
# Group 1, no AI: [1,2]
# Group 2, yes AI: [3,4,5,6]

group1 = df.filter(pl.col("GROUP").is_in([1,2]))["mc1"].to_list()
group2 = df.filter(~pl.col("GROUP").is_in([1,2]))["mc1"].to_list()

In [22]:
_, p = mannwhitneyu(group1, group2)
p

np.float64(0.06284610586110151)

In [23]:
df.group_by("GROUP").agg(pl.col("MC2").mean()).sort(by="GROUP").plot.bar(
    x="GROUP", y="MC2"
)

alt.Chart(...)

In [24]:
# Group 1, positive outcome: 1,3,5
# Group 2, negative outcome: 2,4,6

group1 = df.filter(pl.col("GROUP").is_in([1,3,5]))["MC2"].to_list()
group2 = df.filter(~pl.col("GROUP").is_in([1,3,5]))["MC2"].to_list()

In [25]:
_, p = mannwhitneyu(group1, group2)
p

np.float64(6.345301366559297e-33)